### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by sebastian-raubach** [citation-js/citation-js#156]
I'm using `citation-js@0.5.6` with a Vue setup using Webpack 5. I recently upgraded from Webpack 4 (with citation-js@0.5.1) to 5 and this issue has only started showing up now.

The error I get is this:

```
ReferenceError: process is not defined
    at Module../node_modules/@citation-js/core/lib-mjs/util/fetchFile.js (fetchFile.js:6:55)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Module../node_modules/@citation-js/core/lib-mjs/util/index.js (grammar.js:50:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Module../node_modules/@citation-js/core/lib-mjs/index.js (validate.js:59:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Object../node_modules/citation-js/index.js (index.js:1:14)
```

A bit of Googling suggests, that the `process` in question is something only available in node.js and not in the browser. Does this mean citation-js cannot be used in the browser in `0.5.6`? I had to update from `0.5.1` because of issues addressed here: https://github.com/citation-js/citation-js/issues/130

**Comment by sebastian-raubach** [comment]
I seem to have got it working using this: https://stackoverflow.com/a/64553486/1449199
