### ISSUE TITLE
error while formatting references from Wikidata

### ISSUE THREAD

**Issue by egonw** [citation-js/citation-js#176]
This is the list of Wikidata items of which one causes a problem:

```
Q102043840
Q105037759
Q105833381
Q109348309
Q113367696
Q24567743
Q27042516
Q28740981
Q28843308
Q30491855
Q36641750
Q41799194
Q42896569
Q57793775
Q63433973
Q86729469
Q87000965
Q87461271
Q87830400
Q90557988
Q91131712
Q98169475
Q99196713
Q99440037
```

The error with the last bit of JSON:

```
{
  id: 'Q109640048',
  type: 'item',
  modified: '2022-07-12T19:02:18Z',
  labels: { en: 'João Vitor Ferreira Cavalcante' },
  descriptions: { en: 'researcher' },
  aliases: { en: [ 'João Vitor F. Cavalcante' ] },
  claims: {
    P31: [ [Object] ],
    P496: [ [Object] ],
    P106: [ [Object] ],
    P735: [ [Object] ]
  },
  sitelinks: {}
} { P1545: [ '5' ], P1932: [ 'João Vitor Ferreira Cavalcante' ] } João Vitor Ferreira Cavalcante
TypeError: Cannot read property 'split' of undefined
    at parseName (/home/egonw/var/Projects/hub/SARS-CoV-2-Queries/node_modules/@citation-js/name/lib/input.js:63:34)
    at parseName (/home/egonw/var/Projects/hub/SARS-CoV-2-Queries/node_modules/@citation-js/plugin-wikidata/lib/prop.js:39:33)
    at Array.map (<anonymous>)
    at parseNames (/home/egonw/var/Projects/hub/SARS-CoV-2-Queries/node_modules/@citation-js/plugin-wikidata/lib/prop.js:47:17)
    at parseProp (/home/egonw/var/Projects/hub/SARS-CoV-2-Queries/node_modules/@citation-js/plugin-wikidata/lib/prop.js:90:14)
    at parseEntity (/home/egonw/var/Projects/hub/SARS-CoV-2-Queries/node_modules/@citation-js/plugin-wikidata/lib/entity.js:69:42)
    at Array.map (<anonymous>)
    at Object.parseEntitiesAsync [as @wikidata/object] (/home/egonw/var/Projects/hub/SARS-CoV-2-Queries/node_modules/@citation-js/plugin-wikidata/lib/entity.js:111:48)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async chainAsync (/home/egonw/var/Projects/hub/SARS-CoV-2-Queries/node_modules/@citation-js/core/lib/plugins/input/chain.js:126:18)
```

**Comment by larsgw** [comment]
This seems to be due to a non-breaking space in the author name. These should be handled in the name parsing library, see https://github.com/citation-js/name/issues/3
