### ISSUE TITLE
Error for wd:Q149998

### ISSUE THREAD

**Issue by larsgw** [citation-js/citation-js#41]
```
TypeError: Cannot read property 'P1813' of undefined
    at getPlace (/packages/plugin-wikidata/lib/prop.js:61:50)
    at parseProp (/packages/plugin-wikidata/lib/prop.js:117:14)
    at parseEntity (/packages/plugin-wikidata/lib/entity.js:67:42)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/packages/plugin-wikidata/lib/entity.js:135:50)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/packages/plugin-wikidata/lib/entity.js:20:103)
    at _next (/packages/plugin-wikidata/lib/entity.js:22:194)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by larsgw** [comment]
Underlying problem: it has already fetched `Q17 (country)` (due to a currently unavoidable problem) and decides not to fetch it again, which makes sense. However, this does not immediately fill in the info in the place it's needed.
